apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
spec:
  interval: 30m
  suspend: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/cert-manager/issuers"
  prune: false
  wait: true
  timeout: 5m0s
  targetNamespace: cert-manager
  dependsOn:
    - name: cert-manager
