apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: "test-app"
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    semver: ">0.0.1"
  timeout: 2m
  url: oci://ghcr.io/kostya0banan666/charts/test-app
