apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-app
spec:
  targetNamespace: test-app
  interval: 1h
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: test-app
