apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-app
spec:
  targetNamespace: test-app
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: test-app
      sourceRef:
        kind: OCIRepository
        name: test-app
