apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

patches:
  - target:
      kind: Kustomization
    patch: |
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-gpg
      - op: add
        path: /spec/postBuild
        value:
          substitute:
            cluster_name: "k3s"
