apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  targetNamespace: ingress-nginx
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.13.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        nodePorts:
          http: "30080"
          https: "30443"
      ingressClassResource:
        default: true
