apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allow-acme-from-nginx.yaml

patches:
  - target:
      kind: Kustomization
      name: flux-system
    path: patch-flux-kustomization.yaml
