apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  targetNamespace: podinfo
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: podinfo
      version: "6.9.2"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
