apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../sources/
  - ./apps/
  - ./flux-system/
  - ./receivers/
  - ./infra/

patches:
  - target:
      kind: Kustomization
      name: flux-system
      namespace: flux-system
    patch: |
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-gpg
      - op: add
        path: /spec/postBuild
        value:
          substitute:
            cluster_name: "k3s"
