apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
spec:
  values:
    ntfy:
      baseURL: "https://ntfy.sava777.keenetic.name"
      cache:
        duration: "24h"
      attachment:
        cacheDir: /var/lib/ntfy/attachments

    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: ntfy.sava777.keenetic.name
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
       - secretName: ntfy-tls
         hosts:
           - ntfy.sava777.keenetic.name
