apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  values:
    ui:
      message: "Hello from Flux on k3s 🚀"
      color: "#5865f2"
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - host: demo.sava777.keenetic.name
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: podinfo-tls
          hosts:
            - demo.sava777.keenetic.name
